# Generated by Django 4.2.7 on 2025-04-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formactionfield',
            old_name='label_name',
            new_name='label',
        ),
    ]
