# Generated by Django 4.2.7 on 2025-03-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_controlmaster_controlparametermaster_fieldmaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlparametermaster',
            old_name='parameter_name',
            new_name='control_value',
        ),
        migrations.RemoveField(
            model_name='controlparametermaster',
            name='paramter_value',
        ),
    ]
