# Generated by Django 4.2.7 on 2025-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_rename_parameter_name_controlparametermaster_control_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='controlmaster',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='controlmaster',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
