# Generated by Django 4.2.7 on 2025-03-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_controlmaster_created_at_controlmaster_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldmaster',
            old_name='control_type_id',
            new_name='form_id',
        ),
    ]
