# Generated by Django 4.2.7 on 2025-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_rename_control_type_id_fieldmaster_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSubMaster1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_id', models.TextField(blank=True, null=True)),
                ('control_type_id', models.TextField(blank=True, null=True)),
                ('control_sub_id', models.TextField(blank=True, null=True)),
                ('control_type', models.TextField(blank=True, null=True)),
                ('control_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
