# Generated by Django 4.2.7 on 2025-03-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_controlsubmaster1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='controlsubmaster1',
            table='control_sub_master1',
        ),
    ]
