# Generated by Django 4.2.7 on 2025-03-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_alter_controlsubmaster1_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlsubmaster1',
            name='control_sub_id',
        ),
    ]
