# Generated by Django 4.2.7 on 2025-03-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0010_remove_controlsubmaster1_control_sub_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlmaster',
            old_name='list_of_values',
            new_name='sub_master1',
        ),
        migrations.AddField(
            model_name='controlmaster',
            name='sub_master2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlsubmaster1',
            name='datatype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
