# Generated by Django 4.2.7 on 2025-03-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0011_rename_list_of_values_controlmaster_sub_master1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlsubmaster1',
            old_name='control_type',
            new_name='sub_control_type',
        ),
        migrations.RenameField(
            model_name='controlsubmaster1',
            old_name='control_value',
            new_name='sub_control_value',
        ),
    ]
