# Generated by Django 4.2.7 on 2025-03-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0012_rename_control_type_controlsubmaster1_sub_control_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormMaster',
        ),
    ]
