# Generated by Django 4.2.7 on 2025-03-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0013_delete_formmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_id', models.TextField(blank=True, null=True)),
                ('form_name', models.TextField(blank=True, null=True)),
                ('paramter_name', models.TextField(blank=True, null=True)),
                ('label_name', models.TextField(blank=True, null=True)),
                ('control_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_master',
            },
        ),
    ]
