# Generated by Django 4.2.7 on 2025-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_fieldmaster_sub_control_id_fieldmaster_sub_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldmaster',
            old_name='form_id',
            new_name='form_name',
        ),
        migrations.RemoveField(
            model_name='formmaster',
            name='control_id',
        ),
        migrations.RemoveField(
            model_name='formmaster',
            name='label_name',
        ),
        migrations.RemoveField(
            model_name='formmaster',
            name='paramter_name',
        ),
        migrations.AddField(
            model_name='fieldmaster',
            name='label_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldmaster',
            name='paramter_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
