# Generated by Django 4.2.7 on 2025-03-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0016_rename_form_id_fieldmaster_form_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmaster',
            name='control_master_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
