# Generated by Django 4.2.7 on 2025-03-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_fieldmaster_control_master_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmaster',
            name='form_name',
        ),
    ]
