# Generated by Django 4.2.7 on 2025-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0018_remove_fieldmaster_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmaster',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
