# Generated by Django 4.2.7 on 2025-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0019_fieldmaster_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmaster',
            name='control_id',
        ),
        migrations.RemoveField(
            model_name='fieldmaster',
            name='label_name',
        ),
        migrations.RemoveField(
            model_name='fieldmaster',
            name='paramter_name',
        ),
        migrations.AddField(
            model_name='formmaster',
            name='control_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formmaster',
            name='label_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formmaster',
            name='paramter_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
