# Generated by Django 4.2.7 on 2025-03-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0021_rename_paramter_name_formmaster_parameter_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormMaster',
            new_name='FormFieldMaster',
        ),
        migrations.AlterModelTable(
            name='formfieldmaster',
            table='form_field_master',
        ),
    ]
