# Generated by Django 4.2.7 on 2025-03-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0023_formmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldmaster',
            name='form_name',
        ),
    ]
