# Generated by Django 4.2.7 on 2025-03-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0025_formfieldmaster_control_master_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldmaster',
            name='control_master_id',
        ),
    ]
