# Generated by Django 4.2.7 on 2025-03-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0026_remove_formfieldmaster_control_master_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmaster',
            name='form_field_id',
            field=models.ForeignKey(blank=True, db_column='form_field_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_feild_relation', to='Masters.formfieldmaster'),
        ),
    ]
