# Generated by Django 4.2.7 on 2025-03-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0027_fieldmaster_form_field_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmaster',
            name='form_field_id',
        ),
    ]
