# Generated by Django 4.2.7 on 2025-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0028_remove_fieldmaster_form_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmaster',
            name='control_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldmaster',
            name='form_field_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
