# Generated by Django 4.2.7 on 2025-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0029_fieldmaster_control_id_fieldmaster_form_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldmaster',
            name='order_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
