# Generated by Django 4.2.7 on 2025-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0030_formfieldmaster_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmaster',
            name='control_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlmaster',
            name='sub_master1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlmaster',
            name='sub_master2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlsubmaster1',
            name='control_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlsubmaster1',
            name='control_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmaster',
            name='control_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmaster',
            name='control_master_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmaster',
            name='form_field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmaster',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmaster',
            name='sub_control_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldmaster',
            name='control_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldmaster',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldmaster',
            name='order_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
