# Generated by Django 4.2.7 on 2025-03-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0031_alter_controlmaster_control_type_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('radio', 'Radio Button'), ('dropdown', 'Dropdown')], max_length=20)),
                ('options', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
