# Generated by Django 4.2.7 on 2025-03-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0036_rename_control_id_contromasters_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControMasters',
            new_name='ControlMasters',
        ),
        migrations.RenameField(
            model_name='controlmasters',
            old_name='data_type',
            new_name='datatype',
        ),
    ]
