# Generated by Django 4.2.7 on 2025-03-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0039_formfield_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='row_position',
        ),
    ]
