# Generated by Django 4.2.7 on 2025-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0040_remove_formfield_row_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubControlMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.TextField(blank=True, null=True)),
                ('control_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_control_master',
            },
        ),
    ]
