# Generated by Django 4.2.7 on 2025-03-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0041_subcontrolmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontrolmaster',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_master', to='Masters.formfield'),
        ),
    ]
