# Generated by Django 4.2.7 on 2025-03-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0042_subcontrolmaster_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fielddependency',
            table='field_dependency',
        ),
        migrations.AlterModelTable(
            name='fieldvalidation',
            table='field_validation',
        ),
    ]
