# Generated by Django 4.2.7 on 2025-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0044_alter_subcontrolmaster_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontrolmaster',
            name='field',
        ),
        migrations.AddField(
            model_name='subcontrolmaster',
            name='field_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
