# Generated by Django 4.2.7 on 2025-03-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0045_remove_subcontrolmaster_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='sub_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_id', to='Masters.subcontrolmaster'),
        ),
    ]
