# Generated by Django 4.2.7 on 2025-03-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0046_formfield_sub_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='sub_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
