# Generated by Django 4.2.7 on 2025-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0047_formfield_sub_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalidation',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
