# Generated by Django 4.2.7 on 2025-03-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0048_alter_fieldvalidation_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='sub_control',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='sub_value',
        ),
    ]
