# Generated by Django 4.2.7 on 2025-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0050_form_created_by_form_updated_at_form_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='searchable',
        ),
        migrations.AddField(
            model_name='formfield',
            name='attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
