# Generated by Django 4.2.7 on 2025-03-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0051_remove_formfield_disable_remove_formfield_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalidation',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_validations', to='Masters.form'),
        ),
    ]
