# Generated by Django 4.2.7 on 2025-03-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0052_fieldvalidation_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalidation',
            name='sub_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_validations', to='Masters.subcontrolmaster'),
        ),
    ]
