# Generated by Django 4.2.7 on 2025-03-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0053_fieldvalidation_sub_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalidation',
            name='rule',
        ),
    ]
