# Generated by Django 4.2.7 on 2025-03-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0054_remove_fieldvalidation_rule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubControlMaster',
            new_name='ValidationMaster',
        ),
        migrations.AlterModelTable(
            name='validationmaster',
            table='validation_master',
        ),
    ]
