# Generated by Django 4.2.7 on 2025-03-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0055_rename_subcontrolmaster_validationmaster_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControlMasters',
            new_name='CommonMaster',
        ),
        migrations.AlterModelTable(
            name='commonmaster',
            table='common_master',
        ),
    ]
