# Generated by Django 4.2.7 on 2025-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0056_rename_controlmasters_commonmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddependency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fielddependency',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fielddependency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fielddependency',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
