# Generated by Django 4.2.7 on 2025-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0058_regexpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalidation',
            name='datatype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
