# Generated by Django 4.2.7 on 2025-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0059_fieldvalidation_datatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonmaster',
            name='control_type',
        ),
        migrations.AddField(
            model_name='validationmaster',
            name='datatype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
