# Generated by Django 4.2.7 on 2025-04-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0061_formaction_controlparametermaster_is_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonmaster',
            old_name='datatype',
            new_name='type',
        ),
    ]
