# Generated by Django 4.2.7 on 2025-04-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0063_rename_action_id_formactionfield_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formactionfield',
            old_name='lable_name',
            new_name='label_name',
        ),
    ]
