# Generated by Django 4.2.7 on 2025-04-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0064_rename_lable_name_formactionfield_label_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formactionfield',
            table='form_action_field',
        ),
    ]
