# Generated by Django 4.2.7 on 2025-04-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0065_alter_formactionfield_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='formactionfield',
            name='button_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
