# Generated by Django 4.2.7 on 2025-04-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0068_formfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfile',
            old_name='file_id',
            new_name='file',
        ),
    ]
