# Generated by Django 4.2.7 on 2025-04-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0070_formdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldvalues',
            old_name='form',
            new_name='form_data',
        ),
    ]
