# Generated by Django 4.2.7 on 2025-04-03 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0072_alter_formfieldvalues_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalues',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='Masters.form'),
        ),
    ]
