# Generated by Django 4.2.7 on 2025-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0003_remove_workflow_document_workflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow_action_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField(blank=True, null=True)),
                ('action_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_action_details',
            },
        ),
        migrations.CreateModel(
            name='workflow_action_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField(blank=True, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
                ('action_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_action_master',
            },
        ),
        migrations.CreateModel(
            name='workflow_matrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.TextField(blank=True, null=True)),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('step_name', models.TextField(blank=True, null=True)),
                ('button_type_id', models.IntegerField(blank=True, null=True)),
                ('button_act_details', models.IntegerField(blank=True, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_matrix',
            },
        ),
    ]
